package elokuvarekisteri.test;
// Generated by ComTest BEGIN
import java.io.File;
import elokuvarekisteri.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.22 13:19:56 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class GenretTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta65 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta65() throws SailoException {    // Genret: 65
    Genret genret = new Genret(); 
    Genre genre1 = new Genre("Draama"), genre2 = new Genre("Toiminta"); 
    String hakemisto = "testi"; 
    String tiedNimi = hakemisto+"/elokuvat"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    genret.lueTiedostosta(tiedNimi); 
    fail("Genret: 76 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    genret.lisaa(genre1); 
    genret.lisaa(genre2); 
    genret.tallenna(); 
    genret = new Genret(); 
    genret.lueTiedostosta(tiedNimi); 
    Iterator<Genre> i = genret.iterator(); 
    assertEquals("From: Genret line: 83", genre1.toString(), i.next().toString()); 
    assertEquals("From: Genret line: 84", genre2.toString(), i.next().toString()); 
    assertEquals("From: Genret line: 85", false, i.hasNext()); 
    genret.lisaa(genre2); 
    genret.tallenna(); 
    assertEquals("From: Genret line: 88", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Genret line: 90", true, fbak.delete()); 
    assertEquals("From: Genret line: 91", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator195 */
  @Test
  public void testIterator195() {    // Genret: 195
    Genret genret = new Genret(); 
    Genre toiminta = new Genre("Toiminta"); 
    genret.lisaa(toiminta); 
    Genre draama = new Genre("Draama"); 
    genret.lisaa(draama); 
    Genre supers = new Genre("Supersankari"); 
    genret.lisaa(supers); 
    Genre rikos = new Genre("Rikos"); 
    genret.lisaa(rikos); 
    Genre west = new Genre("Western"); 
    genret.lisaa(west); 
    Iterator<Genre> i2=genret.iterator(); 
    assertEquals("From: Genret line: 212", toiminta, i2.next()); 
    assertEquals("From: Genret line: 213", draama, i2.next()); 
    assertEquals("From: Genret line: 214", supers, i2.next()); 
    assertEquals("From: Genret line: 215", rikos, i2.next()); 
    assertEquals("From: Genret line: 216", west, i2.next()); 
    try {
    assertEquals("From: Genret line: 217", rikos, i2.next()); 
    fail("Genret: 217 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}