package elokuvarekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import elokuvarekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.22 13:19:43 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class GenreTest {



  // Generated by ComTest BEGIN
  /** testGetGenre39 */
  @Test
  public void testGetGenre39() {    // Genre: 39
    Genre genre = new Genre(); 
    genre.parse("1|Toiminta"); 
    assertEquals("From: Genre line: 42", "Toiminta", genre.getGenre()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi63 */
  @Test
  public void testRekisteroi63() {    // Genre: 63
    Genre genre1 = new Genre("Toiminta"); 
    assertEquals("From: Genre line: 65", 0, genre1.getTunnusNro()); 
    genre1.rekisteroi(); 
    Genre genre2 = new Genre("Komedia"); 
    genre2.rekisteroi(); 
    int n1 = genre1.getTunnusNro(); 
    int n2 = genre2.getTunnusNro(); 
    assertEquals("From: Genre line: 71", n2-1, n1); 
  } // Generated by ComTest END
}