package elokuvarekisteri.test;
// Generated by ComTest BEGIN
import java.io.File;
import elokuvarekisteri.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.22 13:20:01 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KatsomistavatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta67 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta67() throws SailoException {    // Katsomistavat: 67
    Katsomistavat katsomistavat = new Katsomistavat(); 
    Katsomistapa kat1 = new Katsomistapa("DVD"), kat2 = new Katsomistapa("Elokuvateatteri"); 
    String hakemisto = "testi"; 
    String tiedNimi = hakemisto+"/elokuvat"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    katsomistavat.lueTiedostosta(tiedNimi); 
    fail("Katsomistavat: 78 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    katsomistavat.lisaa(kat1); 
    katsomistavat.lisaa(kat2); 
    katsomistavat.tallenna(); 
    katsomistavat = new Katsomistavat(); 
    katsomistavat.lueTiedostosta(tiedNimi); 
    Iterator<Katsomistapa> i = katsomistavat.iterator(); 
    assertEquals("From: Katsomistavat line: 85", kat1.toString(), i.next().toString()); 
    assertEquals("From: Katsomistavat line: 86", kat2.toString(), i.next().toString()); 
    assertEquals("From: Katsomistavat line: 87", false, i.hasNext()); 
    katsomistavat.lisaa(kat2); 
    katsomistavat.tallenna(); 
    assertEquals("From: Katsomistavat line: 90", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Katsomistavat line: 92", true, fbak.delete()); 
    assertEquals("From: Katsomistavat line: 93", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator198 */
  @Test
  public void testIterator198() {    // Katsomistavat: 198
    Katsomistavat kat = new Katsomistavat(); 
    Katsomistapa elok = new Katsomistapa("Elokuvateatteri"); 
    kat.lisaa(elok); 
    Katsomistapa dvd = new Katsomistapa("DVD"); 
    kat.lisaa(dvd); 
    Katsomistapa blu = new Katsomistapa("Blu-Ray"); 
    kat.lisaa(blu); 
    Katsomistapa net = new Katsomistapa("Netflix"); 
    kat.lisaa(net); 
    Katsomistapa tv = new Katsomistapa("TV"); 
    kat.lisaa(tv); 
    Iterator<Katsomistapa> i3=kat.iterator(); 
    assertEquals("From: Katsomistavat line: 215", elok, i3.next()); 
    assertEquals("From: Katsomistavat line: 216", dvd, i3.next()); 
    assertEquals("From: Katsomistavat line: 217", blu, i3.next()); 
    assertEquals("From: Katsomistavat line: 218", net, i3.next()); 
    assertEquals("From: Katsomistavat line: 219", tv, i3.next()); 
    try {
    assertEquals("From: Katsomistavat line: 220", net, i3.next()); 
    fail("Katsomistavat: 220 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}