package elokuvarekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import elokuvarekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.22 13:19:49 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KatsomistapaTest {



  // Generated by ComTest BEGIN
  /** testGetKatsomistapa36 */
  @Test
  public void testGetKatsomistapa36() {    // Katsomistapa: 36
    Katsomistapa kat = new Katsomistapa("Elokuvateatteri"); 
    { String _l_=kat.getKatsomistapa(),_r_="Elokuvateatteri"; if ( !_l_.matches(_r_) ) fail("From: Katsomistapa line: 38" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi59 */
  @Test
  public void testRekisteroi59() {    // Katsomistapa: 59
    Katsomistapa katsomistapa1 = new Katsomistapa("Elokuvateatteri"); 
    assertEquals("From: Katsomistapa line: 61", 0, katsomistapa1.getTunnusNro()); 
    katsomistapa1.rekisteroi(); 
    Katsomistapa katsomistapa2 = new Katsomistapa("Blu-Ray"); 
    katsomistapa2.rekisteroi(); 
    int n1 = katsomistapa1.getTunnusNro(); 
    int n2 = katsomistapa2.getTunnusNro(); 
    assertEquals("From: Katsomistapa line: 67", n2-1, n1); 
  } // Generated by ComTest END
}